config:
  entities:
    nodeTypes:
      "173":
        defaultStorageLocation: null
        isDisabled: true
      "188":
        defaultStorageLocation: null
        isDisabled: true
      "194":
        defaultStorageLocation: null
        isDisabled: true
      "204":
        defaultStorageLocation: null
        isDisabled: true
      "205":
        defaultStorageLocation: null
        isDisabled: true
      "248":
        defaultStorageLocation: null
        isDisabled: true
  packageVariables: ""
fileVersion: 1
id: "@coalesce/snowflake/devcopied-base-node-types"
name: base
packageID: "@coalesce/snowflake/devcopied-base-node-types"
releaseID: 68214743-6774-4ff6-8070-bb04b5e20361
type: Package
